name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
    # Artifact name
        name: artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: /
    # The desired behavior if no files are found using the provided path.
        overwrite: true
              
